name: Node.js CI with Docker

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "development"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust the Node.js version as neededd

    - name: Install Dependencies
      run: npm install

    - name: Build Docker Image
      run: docker build -t raj456/nodeci:latest .

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Extract Credentials
    #   id: extract 
    #   run: |
    #     DOCKER_USERNAME=$(echo "$SECRETS" | jq -r '.DOCKER_USERNAME')
    #     DOCKER_PASSWORD=$(echo "$SECRETS" | jq -r '.DOCKER_PASSWORD')
    #     echo "::set-output name=DOCKER_USERNAME::$DOCKER_USERNAME"
    #     echo "::set-output name=DOCKER_PASSWORD::$DOCKER_PASSWORD"

    # - name: Login to Docker registry
    #   run: |
    #       docker login -u $(steps.extract.outputs.DOCKER_USERNAME) -p $(steps.extract.outputs.DOCKER_PASSWORD)

    - name: Extract
      id: extract
      run: |
        DOCKER_USERNAME=$(echo "$SECRETS1" | jq -r '.DOCKER_USERNAME')
        DOCKER_PASSWORD=$(echo "$SECRETS1" | jq -r '.DOCKER_PASSWORD')
        echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> $GITHUB_ENV
        echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> $GITHUB_ENV

    - name: Login to Docker registry
      run: |
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    
    - name: Push Docker Image to Docker Hub
      run: docker push raj456/nodeci:latest
      
    # - name: Get SHA Digest
    #   run: |
    #     SHA_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' pradippipaliya/ci-cd)
    #     printf '{  
    #       "prop_1": "%s" 
    #     }' "$SHA_DIGEST" >> sha_digest.json
    # - name: Upload SHA digest in artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #       name: sha_digest.json
    #       path: ./sha_digest.json
