name: Deploy for Node.js

on:
  push:
    branches:
      - "main"
  workflow_run:
    workflows: ["Node.js CI with Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download SHA Digest Artifact
      uses: actions/download-artifact@v3
      with:
        name: sha_digest
        path: ./sha_digest.txt

    - name: Use SHA Digest
      run: |
        SHA_DIGEST=$(cat ./sha_digest.txt)
        echo "Using SHA Digest: $SHA_DIGEST"
