name: Display SHA Digest

on:
  workflow_run:
    workflows: ["Node.js CI with Docker"]
    types:
      - completed

jobs:
  display_sha_digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download SHA Digest Artifact
        uses: actions/download-artifact@v3
        with:
          name: ./sha_digest.txt

      - name: Show SHA Digest
        run: cat sha_digest.txt
