name: Node.js CI with Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.event.inputs.tag }}
      DOCKER_USERNAME: ${{ github.actor }}

    steps:
      - name: Convert GitHub username to lowercase
        run: |
          export DOCKER_USERNAME_LOWER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          echo "::set-env name=DOCKER_USERNAME_LOWER::${DOCKER_USERNAME_LOWER}"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME_LOWER }}/ci-cd:${{ env.IMAGE_TAG }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ env.DOCKER_USERNAME_LOWER }}/ci-cd:${{ env.IMAGE_TAG }}

      - name: Get SHA Digest
        run: |
          SHA_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.DOCKER_USERNAME_LOWER }}/ci-cd:${{ env.IMAGE_TAG }})
          echo "SHA Digest: $SHA_DIGEST"
          echo "$SHA_DIGEST" > $GITHUB_WORKSPACE/sha_digest.txt
        
      - name: Debugging
        run: |
          ls -al
          pwd

      - name: Commit and Push Changes
        if: github.event_name == 'workflow_dispatch'  # Only execute when triggered manually
        run: |
          git config --global user.email "pradippipaliyainventyv@gmail.com"
          git config --global user.name "Pradip-Inventyv"
          git add $GITHUB_WORKSPACE/sha_digest.txt
          git commit -m "Add SHA Digest file"
          git push https://github.com/Pradip-Inventyv/CI-CD.git HEAD:main
