name: Node.js CI with Docker

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust the Node.js version as needed

    - name: Install Dependencies
      run: npm install

    - name: Build Docker Image
      run: docker build -t pradippipaliya/ci-cd .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Add approval step for two reviewers
    - name: Request Approval
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.PERSONAL_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          const reviewers = ['Raj-inventyv', 'Shivang-inventyv']; // Add your reviewers' usernames here
          await Promise.all(reviewers.map(async (reviewer) => {
            await github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [reviewer]
            });
          }));
          
    # Poll for pull request approvals
    - name: Wait for Approvals
      id: wait-for-approvals
      run: |
        while [[ $(curl -s -H "Authorization: Bearer $PERSONAL_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/reviews | \
                jq -r 'map(select(.state == "APPROVED")) | length') -lt 2 ]]; do
            sleep 10
        done
        
    # Proceed only after approval
    - name: Push Docker Image to Docker Hub
      run: docker push pradippipaliya/ci-cd
      
    - name: Get SHA Digest
      run: |
        SHA_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' pradippipaliya/ci-cd)
        echo "SHA Digest: $SHA_DIGEST"
        echo "$SHA_DIGEST" > $GITHUB_WORKSPACE/sha_digest.txt
        
    - name: Debugging
      run: |
        ls -al
        pwd

    - name: Commit and Push Changes
      run: |
        git config --global user.email "pradippipaliyainventyv@gmail.com"
        git config --global user.name "Pradip-Inventyv"
        git add $GITHUB_WORKSPACE/sha_digest.txt
        git commit -m "Add SHA Digest file"
        git push https://github.com/Pradip-Inventyv/CI-CD.git HEAD:main
